In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape)
np.arange(0,10,2).reshape(5,1)

(1, 5)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
arr3 = np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array :\n", arr)
print("Shape :", arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size(number of elements):",arr.size)
print("Data type",arr.dtype)
print("Item size(in bytes) :",arr.itemsize)

Array :
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of Dimensions: 2
Size(number of elements): 6
Data type int64
Item size(in bytes) : 8


In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print("Addition :", arr1+arr2)
print("Substraction:",arr1-arr2)
print("Multiplication : ",arr1*arr2)
print("Division : ", arr1/arr2)


Addition : [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [13]:
arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[2][1])
print(arr[0:2,2:])
print(arr[1:, 1:3])
arr[0,0] = 100
print(arr)
arr[1:] = 100
arr


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
data = np.array([1,2,3,4,5])
median = np.median(data)
mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)
